name: Email Runner
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Show Username
        run: 'echo "Secrets: ${{ secrets.MAIL_USERNAME }}"' 
      - name: Show pass
        run: 'echo "Secrets: ${{ secrets.MAIL_PASSWORD }}"'
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.office365.com
          # Required mail server port:
          server_port: 587
          # Optional (recommended): mail server username:
          username: support@signify.co.za
          # Optional (recommended) mail server password:
          password: Nuh96946
          # Required mail subject:
          subject: Security Scan - Result
          # Required recipients' addresses:
          to: austin.vdmerwe@signify.co.za
          # Required sender full name (address can be skipped):
          from: Signify Security # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Send email from ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          #html_body: file://README.html
          # Optional carbon copy recipients:
          #cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          #bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          #reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          #in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: false
          # Optional converting Markdown to HTML (set content_type to text/html too):
          #convert_markdown: true
          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: high
